name: Workflow and actions experiments

on:
  push:
    branches:
      - master

jobs:
  strategy-as-a-way-to-abstract:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        working-dir: [ui, server]
        include:
          - working-dir: ui
            node-version: 10.x
          - working-dir: server
            node-version: 12.x

    defaults:
      run:
        working-directory: ${{ matrix.working-dir }}

    env:
      GITHUB_SHORT_SHA_1: ${GITHUB_SHA::8}
      GITHUB_SHORT_SHA_2: $(echo $GITHUB_SHA | cut -c 1-8)

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Export GitHub short sha with bashism
        run: export GITHUB_SHORT_SHA_3=${GITHUB_SHA::8}

      - name: Export GitHub short sha with cut
        run: export GITHUB_SHORT_SHA_4=$(echo $GITHUB_SHA | cut -c 1-8)
      
      - name: Use workflow command to set github short sha env var
        run: echo "::set-env name=GITHUB_SHORT_SHA_5::${GITHUB_SHA::8}"

      - name: Print github short shas
        run: |
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo 
          echo "GITHUB_SHORT_SHA_1: $GITHUB_SHORT_SHA_1"
          echo "GITHUB_SHORT_SHA_2: $GITHUB_SHORT_SHA_2"
          echo "GITHUB_SHORT_SHA_3: $GITHUB_SHORT_SHA_3"
          echo "GITHUB_SHORT_SHA_4: $GITHUB_SHORT_SHA_4"
          echo "GITHUB_SHORT_SHA_5: $GITHUB_SHORT_SHA_5"
          
      - name: Print working directory
        run: pwd

      - name: Verify node version
        run: node -v

      - name: Run index.js
        run: node index.js

      - run: echo "Done!"
